Update pre-commit-.yml

diff --git a/.github/workflows/pre-commit-.yml b/.github/workflows/pre-commit-.yml
--- a/.github/workflows/pre-commit-.yml
+++ b/.github/workflows/pre-commit-.yml
@@ -25,3 +25,9 @@ jobs:
     - name: Run pre-commit checks
       run: |
         pre-commit run --all-files --all
+    - name: Check Pre-commit Status
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Pre-commit checks failed. Aborting workflow."
+          exit 1
+        fi
